export function createBuildingVisual({ THREE, building, config, range }) {
  const group = new THREE.Group()
  const material = new THREE.MeshStandardMaterial({ color: '#33465a', emissive: config.color, emissiveIntensity: 0.24, metalness: 0.92, roughness: 0.14 })
  const accentColor = { autocannon: '#ffd36f', droneBay: '#79caff', barrierNode: '#76eaff', overclockRelay: '#ffcf76', salvageExtractor: '#8dff9c' }[building.type] ?? '#a6a2ff'
  const accent = new THREE.MeshStandardMaterial({ color: accentColor, emissive: accentColor, emissiveIntensity: 1.25, metalness: 0.78, roughness: 0.12 })
  const base = new THREE.Mesh(new THREE.CylinderGeometry(0.53, 0.64, 0.26, 8), material)
  base.position.y = 0.13; group.add(base)
  if (building.type === 'chronoGenerator') { const core = new THREE.Mesh(new THREE.IcosahedronGeometry(0.32, 1), accent); core.position.y = 0.67; const ringA = new THREE.Mesh(new THREE.TorusGeometry(0.46, 0.035, 8, 24), accent); ringA.position.y = 0.68; ringA.rotation.x = Math.PI / 2; const ringB = ringA.clone(); ringB.rotation.set(Math.PI / 3, 0, Math.PI / 5); group.add(core, ringA, ringB) }
  if (building.type === 'autocannon') { const turret = new THREE.Mesh(new THREE.BoxGeometry(0.48, 0.26, 0.48), accent); turret.position.y = 0.42; group.add(turret); for (const x of [-0.14, 0.14]) { const barrel = new THREE.Mesh(new THREE.CylinderGeometry(0.075, 0.1, 0.78, 8), accent); barrel.rotation.x = Math.PI / 2; barrel.position.set(x, 0.51, 0.38); group.add(barrel) } }
  if (building.type === 'droneBay') { const hangar = new THREE.Mesh(new THREE.BoxGeometry(0.96, 0.42, 0.78), material); hangar.position.y = 0.47; const door = new THREE.Mesh(new THREE.BoxGeometry(0.56, 0.22, 0.04), accent); door.position.set(0, 0.5, 0.41); group.add(hangar, door); for (const x of [-0.26, 0.26]) { const drone = new THREE.Mesh(new THREE.SphereGeometry(0.09, 8, 6), accent); drone.position.set(x, 0.82, 0.08); group.add(drone) } }
  if (building.type === 'barrierNode') { const crystal = new THREE.Mesh(new THREE.OctahedronGeometry(0.34, 0), accent); crystal.position.y = 0.72; group.add(crystal); for (let index = 0; index < 3; index += 1) { const pylon = new THREE.Mesh(new THREE.ConeGeometry(0.13, 0.8, 6), accent); const angle = index * Math.PI * 2 / 3; pylon.position.set(Math.cos(angle) * 0.42, 0.46, Math.sin(angle) * 0.42); group.add(pylon) } const dome = new THREE.Mesh(new THREE.SphereGeometry(0.72, 16, 10, 0, Math.PI * 2, 0, Math.PI / 2), new THREE.MeshBasicMaterial({ color: '#8ceaff', transparent: true, opacity: 0.15, depthWrite: false })); dome.position.y = 0.1; group.add(dome) }
  if (building.type === 'overclockRelay') { const dish = new THREE.Mesh(new THREE.TorusGeometry(0.34, 0.06, 8, 24), accent); dish.position.y = 0.62; dish.rotation.x = Math.PI / 2; const antenna = new THREE.Mesh(new THREE.CylinderGeometry(0.035, 0.05, 0.72, 8), accent); antenna.position.y = 0.8; const tip = new THREE.Mesh(new THREE.SphereGeometry(0.1, 10, 8), accent); tip.position.y = 1.18; group.add(dish, antenna, tip) }
  if (building.type === 'salvageExtractor') { const chamber = new THREE.Mesh(new THREE.CylinderGeometry(0.3, 0.42, 0.66, 8), accent); chamber.position.y = 0.55; const arm = new THREE.Mesh(new THREE.CylinderGeometry(0.075, 0.1, 0.82, 8), material); arm.position.set(0.36, 0.82, 0); arm.rotation.z = -Math.PI / 3; const claw = new THREE.Mesh(new THREE.ConeGeometry(0.17, 0.34, 5), accent); claw.position.set(0.72, 0.55, 0); claw.rotation.z = -Math.PI / 2; group.add(chamber, arm, claw) }
  const hasRange = Number.isFinite(config.effect.range)
  const effectRing = new THREE.Mesh(new THREE.RingGeometry(0.985, 1.005, 48), new THREE.MeshBasicMaterial({ color: config.color, transparent: true, opacity: 0.28, side: THREE.DoubleSide, depthWrite: false })); effectRing.rotation.x = -Math.PI / 2; effectRing.position.y = 0.03; effectRing.scale.setScalar(hasRange ? range : 0); effectRing.visible = hasRange; group.add(effectRing)
  let barrierField = null
  if (building.type === 'barrierNode') { barrierField = new THREE.Group(); const wall = new THREE.Mesh(new THREE.CylinderGeometry(1, 1, 1.6, 40, 1, true), new THREE.MeshBasicMaterial({ color: config.color, transparent: true, opacity: 0.16, side: THREE.DoubleSide, depthWrite: false })); wall.position.y = 0.8; const crown = new THREE.Mesh(new THREE.TorusGeometry(1, 0.035, 6, 40), new THREE.MeshBasicMaterial({ color: '#d5ffff', transparent: true, opacity: 0.85, depthWrite: false })); crown.position.y = 1.58; crown.rotation.x = Math.PI / 2; barrierField.add(wall, crown); barrierField.visible = false; group.add(barrierField) }
  group.position.set(building.x, 0, building.z)
  return { group, effectRing, barrierField }
}
