export const GAME = {
  maxPixelRatio: 2,
  arenaSize: 26,
  arenaLimit: 12,
  playerSpeed: 5,
  playerStartHeight: 0.75,
  playerRadius: 1.05,
  cellPickupRadius: 1.15,
  cellCashValue: 1,
  baseCellCashValue: 1,
  initialCellCount: 5,
  initialObstacleTypes: ['regular', 'chaser', 'creeper'],
  cellSpawnInterval: 6,
  slowAuraBaseRange: 4,
  slowAuraBaseEffect: 0.25,
  cellMinDistance: 3,
  chronoCellSpawnInterval: 24,
  chronoCellLifetime: 7,
  chronoCellMinDistance: 4,
  chronoCellChronoshardValue: 1,
  obstacleMinDistance: 4,
  obstacleSpawnInterval: 8,
  obstacleSpawnDecreasePerCell: 0.04,
  regularObstacleLifetime: 15,
  regularObstacleLifetimeIncreasePerCell: 0.1,
  obstacleSpawnWarningDuration: 2,
  bangerExplosionVfxDuration: 0.65,
  bangerPulseStartInterval: 0.9,
  bangerPulseEndInterval: 0.1,
  bangerPulseVfxDuration: 0.55,
  fallingBlockStartHeight: 16,
  obstacleGroundHeight: 0.86,
  fallingBlockGroundHeight: 0.86,
  fallingBlockDuration: 1.8,
  fallingBlockLifetime: 1.9,
  fallingBlockMinInterval: 1.8,
  fallingBlockBaseInterval: 60,
  fallingBlockIntervalPerCell: 0.1,
  fallingRockImpactOffset: 0.8,
  fieryRockFireDuration: 5,
  fieryRockFireRadius: 1.7,
  fieryRockFlameCount: 9,
  fieryRockEmberCount: 12,
  splinterPieceCount: 4,
  splinterPieceDistance: 8,
  splinterPieceDuration: 1,
  shockwaveBaseRadius: 4.5,
  shockwaveBaseInterval: 8,
  shockwavePushDistance: 4.5,
  shockwaveVfxDuration: 0.65,
  shieldInvulnerabilityDuration: 0.85,
  playerDeathVfxDuration: 0.9,
}

export const DIFFICULTY = {
  tier1: {
    extraArenaPadding: 0, // Extra padding added to the arena size and playable area for this difficulty tier. A positive value increases the arena size, while a negative value decreases it.
    cellsRequiredToAdvance: 10, // Number of cells the player must collect to advance to the next difficulty tier.

    cashValueMultiplier: 1, // Multiplier applied to the base cell cash value defined in the GAME constant. A positive value increases the cash value, while a negative value decreases it.

    availableObstacleTypes: ['regular', 'creeper'], // Available obstacle types for this difficulty tier. If an obstacle type is not included here, it will not spawn in this tier.
    obstacleSpawnIntervalOffset: 3, // This offset is added to the base obstacle spawn interval defined in the GAME constant. A positive value increases the interval (slower spawning), while a negative value decreases it (faster spawning).
    obstacleSpawnDecreasePerCellOffset: -0.01, // This offset is added to the base obstacle spawn decrease per cell defined in the GAME constant. A positive value increases the decrease (faster spawning as cells are collected), while a negative value decreases it (slower spawning as cells are collected).
    obstacleLifetimeOffset: -4, // This offset is added to the base obstacle lifetime defined in the GAME constant. A positive value increases the lifetime (obstacles last longer), while a negative value decreases it (obstacles disappear sooner).
    obstacleLifetimeIncreasePerCellOffset: -0.02, // This offset is added to the base obstacle lifetime increase per cell defined in the GAME constant. A positive value increases the increase (obstacles last longer as cells are collected), while a negative value decreases it (obstacles disappear sooner as cells are collected).
    // These weights are used to determine the probability of spawning each obstacle type. The sum isn't normalized, so the actual probability 
    // is calculated by dividing each weight by the sum of all weights. If an obstacle type is not included in the availableObstacleTypes array, its weight is ignored.
    // If an obstacle's weight isn't specified, it defaults to 0.
    regularSpawnWeight: 0.8, // Weight for spawning regular obstacles. A higher value increases the likelihood of spawning this type.
    creeperSpawnWeight: 0.2, // Weight for spawning creeper obstacles. A higher value increases the likelihood of spawning this type.
    availableFallingRockTypes: ['stoneRock'],
    fallingRockSpawnIntervalOffset: 2,
    fallingRockSpawnDecreasePerCellOffset: -0.05,
    stoneRockSpawnWeight: 1,
  },
  tier2: {
    extraArenaPadding: 0,
    cellsRequiredToAdvance: 20,

    cashValueMultiplier: 1.2,

    availableObstacleTypes: ['regular', 'chaser', 'creeper'],
    obstacleSpawnIntervalOffset: 2,
    obstacleSpawnDecreasePerCellOffset: 0,
    obstacleLifetimeOffset: -3,
    obstacleLifetimeIncreasePerCellOffset: 0,
    regularSpawnWeight: 0.8,
    chaserSpawnWeight: 0.1,
    creeperSpawnWeight: 0.1,
    availableFallingRockTypes: ['stoneRock', 'splinter'],
    fallingRockSpawnIntervalOffset: -5,
    fallingRockSpawnDecreasePerCellOffset: -0.02,
    stoneRockSpawnWeight: 0.8,
    splinterSpawnWeight: 0.2,
  },
  tier3: {
    extraArenaPadding: 0,
    cellsRequiredToAdvance: 30,

    cashValueMultiplier: 1.5,

    availableObstacleTypes: ['regular', 'chaser', 'creeper', 'banger'],
    obstacleSpawnIntervalOffset: 1,
    obstacleSpawnDecreasePerCellOffset: 0.01,
    obstacleLifetimeOffset: -2,
    obstacleLifetimeIncreasePerCellOffset: 0.01,
    regularSpawnWeight: 0.7,
    chaserSpawnWeight: 0.1,
    creeperSpawnWeight: 0.1,
    bangerSpawnWeight: 0.1,
    availableFallingRockTypes: ['stoneRock', 'fieryRock', 'splinter'],
    fallingRockSpawnIntervalOffset: -10,
    fallingRockSpawnDecreasePerCellOffset: 0,
    stoneRockSpawnWeight: 0.6,
    fieryRockSpawnWeight: 0.2,
    splinterSpawnWeight: 0.2,
  },
  tier4: {
    extraArenaPadding: 0,
    cellsRequiredToAdvance: 40,

    cashValueMultiplier: 2,

    availableObstacleTypes: ['regular', 'chaser', 'creeper', 'banger'],
    obstacleSpawnIntervalOffset: 0,
    obstacleSpawnDecreasePerCellOffset: 0.02,
    obstacleLifetimeOffset: -1,
    obstacleLifetimeIncreasePerCellOffset: 0.02,
    regularSpawnWeight: 0.6,
    chaserSpawnWeight: 0.15,
    creeperSpawnWeight: 0.15,
    bangerSpawnWeight: 0.1,
    availableFallingRockTypes: ['stoneRock', 'fieryRock', 'splinter'],
    fallingRockSpawnIntervalOffset: -15,
    fallingRockSpawnDecreasePerCellOffset: 0.05,
    stoneRockSpawnWeight: 0.4,
    fieryRockSpawnWeight: 0.35,
    splinterSpawnWeight: 0.25,
  },
}
export const COLORS = {
  background: '#101b25',
  fog: '#101b25',
  floor: '#1d3a46',
  gridMajor: '#50e5bc',
  gridMinor: '#244b59',
  arenaBoundary: '#ff795f',
  player: '#ff795f',
  playerEmissive: '#b72d20',
  playerRing: '#ffe7a0',
  cell: '#63f5cd',
  cellEmissive: '#00b487',
  chronoCell: '#b59aff',
  chronoCellEmissive: '#5933c7',
  slowAura: '#63f5cd',
  obstacle: '#41687c',
  obstacleEmissive: '#07141d',
  chaser: '#c36b55',
  chaserEmissive: '#70281d',
  creeper: '#8d71c5',
  creeperEmissive: '#38265c',
  banger: '#ffb347',
  bangerEmissive: '#8f3100',
  fallingObstacle: '#66869a',
  fallingObstacleEmissive: '#152b3b',
  fieryRock: '#ff6948',
  fieryRockEmissive: '#b11d08',
  splinter: '#d2c27e',
  splinterEmissive: '#675b25',
  fire: '#ff8a38',
  targetShadow: '#020407',
  targetRing: '#ff795f',
}

export const CAMERA = { fov: 52, near: 0.1, far: 100, height: 12, distance: 15, followStrength: 0.06 }
export const SCENE = { fogNear: 16, fogFar: 37, floorMetalness: 0.5, floorRoughness: 0.55 }
export const LIGHTING = { hemisphereSky: '#b8e8ff', hemisphereGround: '#0a1016', hemisphereIntensity: 2.2, key: '#fff4cf', keyIntensity: 3 }

export const ENTITIES = {
  playerCoreRadius: 0.7,
  playerCoreDetail: 1,
  playerCoreEmissiveIntensity: 1.4,
  playerCoreMetalness: 0.35,
  playerCoreRoughness: 0.25,
  playerRingRadius: 0.92,
  playerRingTube: 0.07,
  playerRingRadialSegments: 10,
  playerRingTubularSegments: 32,
  cellRadius: 0.42,
  chronoCellRadius: 0.52,
  chronoCellEmissiveIntensity: 2.4,
  obstacleRadius: 0.86,
  fallingRockDetail: 1,
  obstacleCoreRadius: 0.48,
  obstacleSpikeRadius: 0.2,
  obstacleSpikeHeight: 0.68,
  obstacleSpikeSegments: 5,
  cellEmissiveIntensity: 1.8,
  cellMetalness: 0.25,
  cellRoughness: 0.2,
  obstacleMetalness: 0.6,
  obstacleRoughness: 0.3,
  fallingObstacleEmissiveIntensity: 0.8,
  fallingObstacleMetalness: 0.65,
  fallingObstacleRoughness: 0.25,
  chaserRangeIndicatorWidth: 0.08,
  chaserRangeIndicatorSegments: 64,
  chaserRange: 5,
  bangerRangeMultiplier: 1.5,
  bangerFuseDuration: 3,
  spawnRingInnerRadius: 0.38,
  spawnRingOuterRadius: 0.5,
  spawnRingSegments: 32,
  spawnCueGlowRadius: 1.45,
  spawnCueBeamHeight: 3.2,
  slowAuraRingWidth: 0.1,
  slowAuraRingSegments: 64,
}

export const ANIMATION = {
  playerTurnSpeed: 1.4,
  playerCoreSpinSpeed: 1.8,
  playerRingSpinSpeed: 2.4,
  cellSpinSpeed: 2.2,
  cellBobBaseHeight: 0.8,
  cellBobAmplitude: 0.16,
  cellBobSpeed: 2.4,
  chronoCellSpinSpeed: 3.6,
  chronoCellBobSpeed: 3.2,
  chronoCellBobAmplitude: 0.24,
  obstacleBobBaseHeight: 0.72,
  obstacleBobAmplitude: 0.12,
  obstacleBobSpeed: 1.8,
  fallingObstacleSpinXSpeed: 3,
  fallingObstacleSpinZSpeed: 2,
  targetShadowBaseScale: 0.38,
  targetShadowScaleGrowth: 0.9,
  targetShadowBaseOpacity: 0.32,
  targetShadowOpacityGrowth: 0.56,
  targetRingPulseSpeed: 12,
  targetRingPulseAmount: 0.1,
  targetRingBaseScale: 0.82,
  targetRingScaleGrowth: 0.62,
  targetRingBaseOpacity: 0.95,
  targetRingOpacityFade: 0.4,
  chaserRangeIndicatorBaseOpacity: 0.24,
  chaserRangeIndicatorActiveOpacity: 0.7,
  chaserRangeIndicatorPulseSpeed: 7,
  chaserRangeIndicatorPulseAmount: 0.1,
  bangerFusePulseSpeed: 9,
  bangerFuseEmissiveBaseIntensity: 0.9,
  bangerFuseEmissivePulseAmount: 1.8,
  spawnRingBaseScale: 0.7,
  spawnRingScaleGrowth: 1,
  spawnRingPulseSpeed: 15,
  spawnRingPulseAmount: 0.12,
  spawnRingBaseOpacity: 0.9,
  spawnCueGlowBaseOpacity: 0.2,
  spawnCueGlowPulseAmount: 0.14,
  spawnCueBeamBaseOpacity: 0.26,
}

export const SOUND = {
  masterVolume: 0.16,
  bangerPulseVolume: 0.32,
  fallingObstacleVolume: 0.82,
  cellCollectVolume: 0.26,
  obstacleSummonVolume: 0.17,
  buttonClickVolume: 0.2,
  spatialMaxDistance: 24,
  spatialMinGain: 0.04,
  fallback: {
    bangerPulse: { startFrequency: 180, endFrequency: 860, duration: 0.055, type: 'square' },
    fallingObstacle: { duration: GAME.fallingBlockDuration },
    cellCollect: { startFrequency: 540, endFrequency: 960, duration: 0.13, type: 'triangle' },
    obstacleSummon: { startFrequency: 130, endFrequency: 310, duration: 2, type: 'sine' },
    buttonClick: { startFrequency: 440, endFrequency: 660, duration: 0.07, type: 'square' },
  },
  assets: {
    bangerPulse: '/audio/banger-pulse.wav',
    fallingObstacle: '/audio/falling-obstacle.wav',
    cellCollect: '/audio/cell-collect.wav',
    obstacleSummon: '/audio/obstacle-summon.wav',
    buttonClick: '/audio/button-click.wav',
  },
}

export const OBSTACLE_TYPES = {
  regular: { color: COLORS.obstacle, emissive: COLORS.obstacleEmissive, speed: 0, range: 0 },
  chaser: { color: COLORS.chaser, emissive: COLORS.chaserEmissive, speed: GAME.playerSpeed / 2, range: ENTITIES.chaserRange },
  creeper: { color: COLORS.creeper, emissive: COLORS.creeperEmissive, speed: GAME.playerSpeed / 4, range: Infinity },
  banger: { color: COLORS.banger, emissive: COLORS.bangerEmissive, speed: 0, range: ENTITIES.chaserRange * ENTITIES.bangerRangeMultiplier },
}

export const FALLING_ROCK_TYPES = {
  stoneRock: { name: 'Stone Rock', color: COLORS.fallingObstacle, emissive: COLORS.fallingObstacleEmissive, emissiveIntensity: ENTITIES.fallingObstacleEmissiveIntensity },
  fieryRock: { name: 'Fiery Rock', color: COLORS.fieryRock, emissive: COLORS.fieryRockEmissive, emissiveIntensity: 2.1 },
  splinter: { name: 'Splinter', color: COLORS.splinter, emissive: COLORS.splinterEmissive, emissiveIntensity: 1.2 },
}
