export const GAME = {
  maxPixelRatio: 2,
  difficultyPressureMultiplier: 0.88,
  obstacleSpawnCount: 2, // Enemy spawn count per spawn event.
  arenaSize: 26,
  arenaLimit: 12,
  playerSpeed: 5,
  playerStartHeight: 0.75,
  playerRadius: 1.05,
  cellPickupRadius: 1.15,
  cellCashValue: 1,
  baseCellCashValue: 1,
  initialCellCount: 5,
  initialObstacleTypes: ['regular', 'chaser', 'creeper'],
  cellSpawnInterval: 5,
  cellMagnetRange: 4,
  cellMagnetBaseSpeed: 0.8,
  boosterSpawnInterval: 18,
  speedBoosterBaseDuration: 5,
  thornShieldBaseDuration: 4,
  freezerBaseDuration: 3,
  pushbackBaseRange: 3.5,
  pushbackBaseSpeed: 0.7,
  slowAuraBaseRange: 4,
  slowAuraBaseEffect: 0.25,
  orbitalElectronOrbitRadius: 3.5,
  orbitalElectronBaseSpeed: 2.1,
  orbitalElectronBaseStunDuration: 0.65,
  orbitalElectronHitRadius: 0.28,
  cellMinDistance: 3,
  chronoCellSpawnInterval: 24,
  chronoCellLifetime: 7,
  chronoCellMinDistance: 4,
  chronoCellChronoshardValue: 1,
  obstacleMinDistance: 4,
  obstacleColliderRadius: 0.86,
  obstacleColliderIterations: 2,
  creeperStaticCollisionSlowDuration: 0.35,
  creeperStaticCollisionSpeedMultiplier: 0.45,
  obstacleSpawnInterval: 7.85,
  obstacleSpawnDecreasePerCell: 0.07,
  regularObstacleLifetime: 32,
  regularObstacleLifetimeIncreasePerCell: 0.14,
  obstacleDespawnWarningDuration: 2,
  obstacleDespawnWarningStartFrequency: 1.2,
  obstacleDespawnWarningEndFrequency: 10,
  obstacleSpawnWarningDuration: 2,
  bangerExplosionVfxDuration: 0.65,
  bangerPulseStartInterval: 0.9,
  bangerPulseEndInterval: 0.1,
  bangerPulseVfxDuration: 0.55,
  fallingBlockStartHeight: 16,
  obstacleGroundHeight: 0.86,
  fallingBlockGroundHeight: 0.86,
  fallingBlockDuration: 1.8,
  fallingBlockLifetime: 1.9,
  fallingBlockMinInterval: 1.8,
  fallingBlockBaseInterval: 24,
  fallingBlockIntervalPerCell: 0.1,
  fallingRockImpactOffset: 0.8,
  fieryRockFireDuration: 5,
  fieryRockFireRadius: 1.7,
  fieryRockFlameCount: 9,
  fieryRockEmberCount: 12,
  splinterPieceCount: 4,
  splinterPieceDistance: 8,
  splinterPieceDuration: 1,
  shockwaveBaseRadius: 4.5,
  shockwaveBaseInterval: 8,
  shockwavePushDistance: 4.5,
  shockwaveVfxDuration: 0.65,
  shieldInvulnerabilityDuration: 1,
  playerDeathVfxDuration: 0.9,
}

export const DIFFICULTY = {
  tier1: {
    extraArenaPadding: 0, // Extra padding added to the arena size and playable area for this difficulty tier. A positive value increases the arena size, while a negative value decreases it.
    cellsRequiredToAdvance: 30, // Number of cells the player must collect to advance to the next difficulty tier.

    cashValueMultiplier: 1, // Multiplier applied to the base cell cash value defined in the GAME constant. A positive value increases the cash value, while a negative value decreases it.

    availableObstacleTypes: ['regular', 'creeper'],
    maxActiveEnemies: 10,
    maxActiveEnemiesIncrementPerCell: 0.03, // Increment applied to the maxActiveEnemies value for each cell collected by the player. A positive value increases the maxActiveEnemies, while a negative value decreases it.
    obstacleSpawnCountOffset: 0,
    obstacleSpawnCountIncreasePerCell: 0.035,
    obstacleSpawnIntervalOffset: 1.8,
    obstacleSpawnDecreasePerCellOffset: 0.002,
    obstacleLifetimeOffset: -7,
    obstacleLifetimeIncreasePerCellOffset: -0.03,
    // These weights are used to determine the probability of spawning each obstacle type. The sum isn't normalized, so the actual probability 
    // is calculated by  dividing each weight by the sum of all weights. If an obstacle type is not included in the availableObstacleTypes array, its weight is ignored.
    // If an obstacle's weight isn't specified, it defaults to 0.
    regularSpawnWeight: 0.7,
    creeperSpawnWeight: 0.3,

    availableFallingRockTypes: ['stoneRock'],
    fallingRockSpawnIntervalOffset: 1.5,
    fallingRockSpawnDecreasePerCellOffset: -0.04,

    stoneRockSpawnWeight: 1,
  },
  tier2: {
    extraArenaPadding: 1,
    cellsRequiredToAdvance: 100,

    cashValueMultiplier: 2,

    availableObstacleTypes: ['regular', 'chaser', 'creeper'],
    maxActiveEnemies: 11,
    maxActiveEnemiesIncrementPerCell: 0.04,
    obstacleSpawnCountOffset: 1,
    obstacleSpawnCountIncreasePerCell: 0.047,
    obstacleSpawnIntervalOffset: 0.6,
    obstacleSpawnDecreasePerCellOffset: 0.014,
    obstacleLifetimeOffset: -4.8,
    obstacleLifetimeIncreasePerCellOffset: 0.012,
    regularSpawnWeight: 0.6,
    chaserSpawnWeight: 0.2,
    creeperSpawnWeight: 0.2,

    availableFallingRockTypes: ['stoneRock', 'splinter'],
    fallingRockSpawnIntervalOffset: -5.8,
    fallingRockSpawnDecreasePerCellOffset: -0.01,

    stoneRockSpawnWeight: 0.8,
    splinterSpawnWeight: 0.2,
  },
  tier3: {
    extraArenaPadding: 2,
    cellsRequiredToAdvance: 200,

    cashValueMultiplier: 4,

    availableObstacleTypes: ['regular', 'chaser', 'creeper', 'banger', 'shooter'],
    maxActiveEnemies: 13,
    maxActiveEnemiesIncrementPerCell: 0.05,
    obstacleSpawnCountOffset: 2,
    obstacleSpawnCountIncreasePerCell: 0.06,
    obstacleSpawnIntervalOffset: -0.4,
    obstacleSpawnDecreasePerCellOffset: 0.025,
    obstacleLifetimeOffset: -2.4,
    obstacleLifetimeIncreasePerCellOffset: 0.032,
    regularSpawnWeight: 0.6,
    chaserSpawnWeight: 0.1,
    creeperSpawnWeight: 0.1,
    bangerSpawnWeight: 0.1,
    shooterSpawnWeight: 0.1,

    availableFallingRockTypes: ['stoneRock', 'fieryRock', 'splinter'],
    fallingRockSpawnIntervalOffset: -11,
    fallingRockSpawnDecreasePerCellOffset: 0.015,

    stoneRockSpawnWeight: 0.6,
    fieryRockSpawnWeight: 0.2,
    splinterSpawnWeight: 0.2,
  },
  tier4: {
    extraArenaPadding: 3,
    cellsRequiredToAdvance: 300,

    cashValueMultiplier: 8,

    availableObstacleTypes: ['regular', 'chaser', 'creeper', 'banger', 'shooter'],
    maxActiveEnemies: 14,
    maxActiveEnemiesIncrementPerCell: 0.06,
    obstacleSpawnCountOffset: 3,
    obstacleSpawnCountIncreasePerCell: 0.072,
    obstacleSpawnIntervalOffset: -0.9,
    obstacleSpawnDecreasePerCellOffset: 0.03,
    obstacleLifetimeOffset: -0.2,
    obstacleLifetimeIncreasePerCellOffset: 0.052,
    regularSpawnWeight: 0.5,
    chaserSpawnWeight: 0.16,
    creeperSpawnWeight: 0.14,
    bangerSpawnWeight: 0.1,
    shooterSpawnWeight: 0.1,

    availableFallingRockTypes: ['stoneRock', 'fieryRock', 'splinter'],
    fallingRockSpawnIntervalOffset: -16.2,
    fallingRockSpawnDecreasePerCellOffset: 0.065,

    stoneRockSpawnWeight: 0.4,
    fieryRockSpawnWeight: 0.35,
    splinterSpawnWeight: 0.25,
  },
  tier5: {
    extraArenaPadding: 4,
    cellsRequiredToAdvance: 300,
    cashValueMultiplier: 16,
    availableObstacleTypes: ['regular', 'chaser', 'creeper', 'banger', 'shooter', 'porter'],
    maxActiveEnemies: 16,
    maxActiveEnemiesIncrementPerCell: 0.07,
    obstacleSpawnCountOffset: 5,
    obstacleSpawnCountIncreasePerCell: 0.085,
    obstacleSpawnIntervalOffset: -1.9,
    obstacleSpawnDecreasePerCellOffset: 0.042,
    obstacleLifetimeOffset: 2,
    obstacleLifetimeIncreasePerCellOffset: 0.076,
    regularSpawnWeight: 0.42,
    chaserSpawnWeight: 0.2,
    creeperSpawnWeight: 0.15,
    bangerSpawnWeight: 0.12,
    shooterSpawnWeight: 0.11,
    porterSpawnWeight: 0.08,
    availableFallingRockTypes: ['stoneRock', 'fieryRock', 'splinter'],
    fallingRockSpawnIntervalOffset: -18.4,
    fallingRockSpawnDecreasePerCellOffset: 0.088,
    stoneRockSpawnWeight: 0.3,
    fieryRockSpawnWeight: 0.42,
    splinterSpawnWeight: 0.28,
  },
  tier6: {
    extraArenaPadding: 5,
    cellsRequiredToAdvance: 300,
    cashValueMultiplier: 32,
    availableObstacleTypes: ['regular', 'chaser', 'creeper', 'banger', 'shooter', 'porter', 'magnet'],
    maxActiveEnemies: 17,
    maxActiveEnemiesIncrementPerCell: 0.08,
    obstacleSpawnCountOffset: 6,
    obstacleSpawnCountIncreasePerCell: 0.097,
    obstacleSpawnIntervalOffset: -2.8,
    obstacleSpawnDecreasePerCellOffset: 0.054,
    obstacleLifetimeOffset: 4.2,
    obstacleLifetimeIncreasePerCellOffset: 0.1,
    regularSpawnWeight: 0.34,
    chaserSpawnWeight: 0.23,
    creeperSpawnWeight: 0.16,
    bangerSpawnWeight: 0.14,
    shooterSpawnWeight: 0.13,
    porterSpawnWeight: 0.1,
    magnetSpawnWeight: 0.09,
    availableFallingRockTypes: ['stoneRock', 'fieryRock', 'splinter'],
    fallingRockSpawnIntervalOffset: -20.6,
    fallingRockSpawnDecreasePerCellOffset: 0.112,
    stoneRockSpawnWeight: 0.24,
    fieryRockSpawnWeight: 0.47,
    splinterSpawnWeight: 0.29,
  },
  tier7: {
    extraArenaPadding: 6,
    cellsRequiredToAdvance: 300,
    cashValueMultiplier: 64,
    availableObstacleTypes: ['regular', 'chaser', 'creeper', 'banger', 'shooter', 'porter', 'magnet', 'spore'],
    maxActiveEnemies: 19,
    maxActiveEnemiesIncrementPerCell: 0.09,
    obstacleSpawnCountOffset: 7,
    obstacleSpawnCountIncreasePerCell: 0.11,
    obstacleSpawnIntervalOffset: -3.7,
    obstacleSpawnDecreasePerCellOffset: 0.066,
    obstacleLifetimeOffset: 6.6,
    obstacleLifetimeIncreasePerCellOffset: 0.124,
    regularSpawnWeight: 0.28,
    chaserSpawnWeight: 0.26,
    creeperSpawnWeight: 0.17,
    bangerSpawnWeight: 0.15,
    shooterSpawnWeight: 0.14,
    porterSpawnWeight: 0.11,
    magnetSpawnWeight: 0.11,
    sporeSpawnWeight: 0.1,
    availableFallingRockTypes: ['stoneRock', 'fieryRock', 'splinter'],
    fallingRockSpawnIntervalOffset: -22.7,
    fallingRockSpawnDecreasePerCellOffset: 0.136,
    stoneRockSpawnWeight: 0.18,
    fieryRockSpawnWeight: 0.51,
    splinterSpawnWeight: 0.31,
  },
  tier8: {
    extraArenaPadding: 7,
    cellsRequiredToAdvance: 300,
    cashValueMultiplier: 128,
    availableObstacleTypes: ['regular', 'chaser', 'creeper', 'banger', 'shooter', 'porter', 'magnet', 'spore'],
    maxActiveEnemies: 20,
    maxActiveEnemiesIncrementPerCell: 0.1,
    obstacleSpawnCountOffset: 8,
    obstacleSpawnCountIncreasePerCell: 0.123,
    obstacleSpawnIntervalOffset: -4.6,
    obstacleSpawnDecreasePerCellOffset: 0.078,
    obstacleLifetimeOffset: 9.2,
    obstacleLifetimeIncreasePerCellOffset: 0.148,
    regularSpawnWeight: 0.22,
    chaserSpawnWeight: 0.29,
    creeperSpawnWeight: 0.18,
    bangerSpawnWeight: 0.16,
    shooterSpawnWeight: 0.15,
    porterSpawnWeight: 0.12,
    magnetSpawnWeight: 0.13,
    sporeSpawnWeight: 0.12,
    availableFallingRockTypes: ['stoneRock', 'fieryRock', 'splinter'],
    fallingRockSpawnIntervalOffset: -24.5,
    fallingRockSpawnDecreasePerCellOffset: 0.16,
    stoneRockSpawnWeight: 0.14,
    fieryRockSpawnWeight: 0.54,
    splinterSpawnWeight: 0.32,
  },
}
export const COLORS = {
  background: '#101b25',
  fog: '#101b25',
  floor: '#1d3a46',
  gridMajor: '#50e5bc',
  gridMinor: '#244b59',
  arenaBoundary: '#ff795f',
  player: '#ff795f',
  playerEmissive: '#b72d20',
  playerRing: '#ffe7a0',
  cell: '#63f5cd',
  cellEmissive: '#00b487',
  chronoCell: '#b59aff',
  chronoCellEmissive: '#5933c7',
  slowAura: '#63f5cd',
  obstacle: '#41687c',
  obstacleEmissive: '#07141d',
  chaser: '#c36b55',
  chaserEmissive: '#70281d',
  creeper: '#8d71c5',
  creeperEmissive: '#38265c',
  banger: '#ffb347',
  bangerEmissive: '#8f3100',
  shooter: '#63f58a',
  shooterEmissive: '#086b35',
  porter: '#4ba3ff',
  porterEmissive: '#124b9e',
  magnet: '#050505',
  magnetEmissive: '#171717',
  spore: '#d990ff',
  sporeEmissive: '#5e1b86',
  fallingObstacle: '#66869a',
  fallingObstacleEmissive: '#152b3b',
  fieryRock: '#ff6948',
  fieryRockEmissive: '#b11d08',
  splinter: '#d2c27e',
  splinterEmissive: '#675b25',
  fire: '#ff8a38',
  targetShadow: '#020407',
  targetRing: '#ff795f',
}

export const CAMERA = { fov: 52, near: 0.1, far: 100, height: 12, distance: 15, portraitDistanceMultiplier: 1.18, followStrength: 0.06 }
export const SCENE = {
  fogNear: 16,
  fogFar: 37,
  floorMetalness: 0.5,
  floorRoughness: 0.55,
  floorOpacity: 0.76,
  starCount: 720,
  brightStarCount: 70,
  starfieldRadius: 70,
  starSize: 1.55,
  brightStarSize: 3.1,
}
export const LIGHTING = { hemisphereSky: '#b8e8ff', hemisphereGround: '#0a1016', hemisphereIntensity: 2.2, key: '#fff4cf', keyIntensity: 3 }

export const ENTITIES = {
  playerCoreRadius: 0.7,
  playerCoreDetail: 1,
  playerCoreEmissiveIntensity: 1.4,
  playerCoreMetalness: 0.35,
  playerCoreRoughness: 0.25,
  playerRingRadius: 0.92,
  playerRingTube: 0.07,
  playerRingRadialSegments: 10,
  playerRingTubularSegments: 32,
  cellRadius: 0.42,
  chronoCellRadius: 0.52,
  chronoCellEmissiveIntensity: 2.4,
  obstacleRadius: 0.86,
  fallingRockDetail: 1,
  obstacleCoreRadius: 0.48,
  obstacleSpikeRadius: 0.2,
  obstacleSpikeHeight: 0.68,
  obstacleSpikeSegments: 5,
  cellEmissiveIntensity: 1.8,
  cellMetalness: 0.25,
  cellRoughness: 0.2,
  obstacleMetalness: 0.6,
  obstacleRoughness: 0.3,
  fallingObstacleEmissiveIntensity: 0.8,
  fallingObstacleMetalness: 0.65,
  fallingObstacleRoughness: 0.25,
  chaserRangeIndicatorWidth: 0.08,
  chaserRangeIndicatorSegments: 64,
  chaserRange: 5,
  bangerRangeMultiplier: 1.5,
  bangerFuseDuration: 3,
  shooterRangeMultiplier: 2,
  shooterProjectileRadius: 0.24,
  shooterProjectileSpeed: 7.5,
  shooterProjectileLifetime: 2.4,
  shooterProjectileCooldown: 2,
  porterTeleportInterval: 10,
  porterWarningDuration: 2,
  porterTeleportMinDistance: 3,
  porterTeleportMaxDistance: 7,
  magnetPullSpeed: 1.1,
  sporeFuseDuration: 3,
  sporeCount: 5,
  sporeRadius: 0.16,
  sporeSpeed: 2.4,
  spawnRingInnerRadius: 0.38,
  spawnRingOuterRadius: 0.5,
  spawnRingSegments: 32,
  spawnCueGlowRadius: 1.45,
  spawnCueBeamHeight: 3.2,
  slowAuraRingWidth: 0.1,
  slowAuraRingSegments: 64,
}

export const ANIMATION = {
  playerTurnSpeed: 1.4,
  playerCoreSpinSpeed: 1.8,
  playerRingSpinSpeed: 2.4,
  cellSpinSpeed: 2.2,
  cellBobBaseHeight: 0.8,
  cellBobAmplitude: 0.16,
  cellBobSpeed: 2.4,
  chronoCellSpinSpeed: 3.6,
  chronoCellBobSpeed: 3.2,
  chronoCellBobAmplitude: 0.24,
  obstacleBobBaseHeight: 0.72,
  obstacleBobAmplitude: 0.12,
  obstacleBobSpeed: 1.8,
  fallingObstacleSpinXSpeed: 3,
  fallingObstacleSpinZSpeed: 2,
  targetShadowBaseScale: 0.38,
  targetShadowScaleGrowth: 0.9,
  targetShadowBaseOpacity: 0.32,
  targetShadowOpacityGrowth: 0.56,
  targetRingPulseSpeed: 12,
  targetRingPulseAmount: 0.1,
  targetRingBaseScale: 0.82,
  targetRingScaleGrowth: 0.62,
  targetRingBaseOpacity: 0.95,
  targetRingOpacityFade: 0.4,
  chaserRangeIndicatorBaseOpacity: 0.24,
  chaserRangeIndicatorActiveOpacity: 0.7,
  chaserRangeIndicatorPulseSpeed: 7,
  chaserRangeIndicatorPulseAmount: 0.1,
  bangerFusePulseSpeed: 9,
  bangerFuseEmissiveBaseIntensity: 0.9,
  bangerFuseEmissivePulseAmount: 1.8,
  spawnRingBaseScale: 0.7,
  spawnRingScaleGrowth: 1,
  spawnRingPulseSpeed: 15,
  spawnRingPulseAmount: 0.12,
  spawnRingBaseOpacity: 0.9,
  spawnCueGlowBaseOpacity: 0.2,
  spawnCueGlowPulseAmount: 0.14,
  spawnCueBeamBaseOpacity: 0.26,
}

export const SOUND = {
  masterVolume: 0.16,
  bangerPulseVolume: 0.32,
  fallingObstacleVolume: 0.82,
  cellCollectVolume: 0.26,
  obstacleSummonVolume: 0.17,
  buttonClickVolume: 0.2,
  spatialMaxDistance: 24,
  spatialMinGain: 0.04,
  fallback: {
    bangerPulse: { startFrequency: 180, endFrequency: 860, duration: 0.055, type: 'square' },
    fallingObstacle: { duration: GAME.fallingBlockDuration },
    cellCollect: { startFrequency: 540, endFrequency: 960, duration: 0.13, type: 'triangle' },
    obstacleSummon: { startFrequency: 130, endFrequency: 310, duration: 2, type: 'sine' },
    buttonClick: { startFrequency: 440, endFrequency: 660, duration: 0.07, type: 'square' },
  },
  assets: {
    bangerPulse: './audio/banger-pulse.wav',
    fallingObstacle: './audio/falling-obstacle.wav',
    cellCollect: './audio/cell-collect.wav',
    obstacleSummon: './audio/obstacle-summon.wav',
    buttonClick: './audio/button-click.wav',
  },
}

export const ENEMY_TYPES = {
  regular: { color: COLORS.obstacle, emissive: COLORS.obstacleEmissive, speed: 0, range: 0 },
  chaser: { color: COLORS.chaser, emissive: COLORS.chaserEmissive, speed: GAME.playerSpeed / 2, range: ENTITIES.chaserRange },
  creeper: { color: COLORS.creeper, emissive: COLORS.creeperEmissive, speed: GAME.playerSpeed / 4, range: Infinity },
  banger: { color: COLORS.banger, emissive: COLORS.bangerEmissive, speed: 0, range: ENTITIES.chaserRange * ENTITIES.bangerRangeMultiplier },
  shooter: { color: COLORS.shooter, emissive: COLORS.shooterEmissive, speed: 0, range: ENTITIES.chaserRange * ENTITIES.shooterRangeMultiplier },
  porter: { color: COLORS.porter, emissive: COLORS.porterEmissive, speed: 0, range: 0 },
  magnet: { color: COLORS.magnet, emissive: COLORS.magnetEmissive, speed: 0, range: ENTITIES.chaserRange },
  spore: { color: COLORS.spore, emissive: COLORS.sporeEmissive, speed: 0, range: 0 },
}

export const FALLING_ROCK_TYPES = {
  stoneRock: { name: 'Stone Rock', color: COLORS.fallingObstacle, emissive: COLORS.fallingObstacleEmissive, emissiveIntensity: ENTITIES.fallingObstacleEmissiveIntensity },
  fieryRock: { name: 'Fiery Rock', color: COLORS.fieryRock, emissive: COLORS.fieryRockEmissive, emissiveIntensity: 2.1 },
  splinter: { name: 'Splinter', color: COLORS.splinter, emissive: COLORS.splinterEmissive, emissiveIntensity: 1.2 },
}
