export const GAME = {
  maxPixelRatio: 2,
  arenaSize: 28,
  arenaLimit: 10.5,
  playerSpeed: 7,
  playerStartHeight: 0.75,
  playerRadius: 1.05,
  cellPickupRadius: 1.15,
  initialCellCount: 5,
  initialObstacleTypes: ['regular', 'chaser', 'creeper'],
  cellSpawnInterval: 6,
  cellMinDistance: 3,
  obstacleMinDistance: 4,
  regularObstacleSpawnInterval: 6,
  regularObstacleLifetime: 18,
  regularObstacleSpawnWarningDuration: 1,
  fallingBlockStartHeight: 15,
  obstacleGroundHeight: 0.86,
  fallingBlockGroundHeight: 0.86,
  fallingBlockDuration: 1.8,
  fallingBlockLifetime: 2.18,
  fallingBlockMinInterval: 1.8,
  fallingBlockBaseInterval: 6,
  fallingBlockIntervalPerCell: 0.35,
}

export const COLORS = {
  background: '#101b25',
  fog: '#101b25',
  floor: '#1d3a46',
  gridMajor: '#50e5bc',
  gridMinor: '#244b59',
  player: '#ff795f',
  playerEmissive: '#b72d20',
  playerRing: '#ffe7a0',
  cell: '#63f5cd',
  cellEmissive: '#00b487',
  obstacle: '#41687c',
  obstacleEmissive: '#07141d',
  chaser: '#c36b55',
  chaserEmissive: '#70281d',
  creeper: '#8d71c5',
  creeperEmissive: '#38265c',
  fallingObstacle: '#66869a',
  fallingObstacleEmissive: '#152b3b',
  targetShadow: '#020407',
  targetRing: '#ff795f',
  regularSpawnRing: '#63f5cd',
}

export const CAMERA = { fov: 52, near: 0.1, far: 100, height: 12, distance: 15, followStrength: 0.06 }
export const SCENE = { fogNear: 16, fogFar: 37, floorMetalness: 0.5, floorRoughness: 0.55 }
export const LIGHTING = { hemisphereSky: '#b8e8ff', hemisphereGround: '#0a1016', hemisphereIntensity: 2.2, key: '#fff4cf', keyIntensity: 3 }

export const ENTITIES = {
  playerCoreRadius: 0.7,
  playerCoreDetail: 1,
  playerCoreEmissiveIntensity: 1.4,
  playerCoreMetalness: 0.35,
  playerCoreRoughness: 0.25,
  playerRingRadius: 0.92,
  playerRingTube: 0.07,
  playerRingRadialSegments: 10,
  playerRingTubularSegments: 32,
  cellRadius: 0.42,
  obstacleRadius: 0.86,
  obstacleDetail: 2,
  obstacleSpikeAmplitude: 0.34,
  cellEmissiveIntensity: 1.8,
  cellMetalness: 0.25,
  cellRoughness: 0.2,
  obstacleMetalness: 0.6,
  obstacleRoughness: 0.3,
  fallingObstacleEmissiveIntensity: 0.8,
  fallingObstacleMetalness: 0.65,
  fallingObstacleRoughness: 0.25,
  chaserRangeIndicatorWidth: 0.08,
  chaserRangeIndicatorSegments: 64,
  regularSpawnRingInnerRadius: 0.38,
  regularSpawnRingOuterRadius: 0.5,
  regularSpawnRingSegments: 32,
}

export const ANIMATION = {
  playerTurnSpeed: 1.4,
  playerCoreSpinSpeed: 1.8,
  playerRingSpinSpeed: 2.4,
  cellSpinSpeed: 2.2,
  cellBobBaseHeight: 0.8,
  cellBobAmplitude: 0.16,
  cellBobSpeed: 2.4,
  obstacleBobBaseHeight: 0.72,
  obstacleBobAmplitude: 0.12,
  obstacleBobSpeed: 1.8,
  fallingObstacleSpinXSpeed: 3,
  fallingObstacleSpinZSpeed: 2,
  targetShadowBaseScale: 0.38,
  targetShadowScaleGrowth: 0.9,
  targetShadowBaseOpacity: 0.32,
  targetShadowOpacityGrowth: 0.56,
  targetRingPulseSpeed: 12,
  targetRingPulseAmount: 0.1,
  targetRingBaseScale: 0.82,
  targetRingScaleGrowth: 0.62,
  targetRingBaseOpacity: 0.95,
  targetRingOpacityFade: 0.4,
  chaserRangeIndicatorBaseOpacity: 0.24,
  chaserRangeIndicatorActiveOpacity: 0.7,
  chaserRangeIndicatorPulseSpeed: 7,
  chaserRangeIndicatorPulseAmount: 0.1,
  regularSpawnRingBaseScale: 0.7,
  regularSpawnRingScaleGrowth: 1,
  regularSpawnRingPulseSpeed: 15,
  regularSpawnRingPulseAmount: 0.12,
  regularSpawnRingBaseOpacity: 0.9,
}

export const OBSTACLE_TYPES = {
  regular: { color: COLORS.obstacle, emissive: COLORS.obstacleEmissive, speed: 0, range: 0 },
  chaser: { color: COLORS.chaser, emissive: COLORS.chaserEmissive, speed: GAME.playerSpeed / 2, range: 5 },
  creeper: { color: COLORS.creeper, emissive: COLORS.creeperEmissive, speed: GAME.playerSpeed / 4, range: Infinity },
}