// Each tier tracks its own best completed run. Every tier uses these six milestones.
const CELL_TARGETS = [10, 25, 50, 100, 250, 500]
const milestone = (tier, index, rewards) => ({ id: `tier-${tier}-${CELL_TARGETS[index]}`, tier, cells: CELL_TARGETS[index], rewards })
const cash = (amount) => ({ type: 'cash', amount })
const chronoshards = (amount) => ({ type: 'chronoshards', amount })
const research = (...researchIds) => ({ type: 'research', researchIds })
const nextTier = (tier) => ({ type: 'tier', tier })

export const MILESTONES = [
  milestone(1, 0, [cash(25), research('initial-cell-count')]), milestone(1, 1, [cash(50), research('cash-cell-multiplier')]), milestone(1, 2, [cash(75), chronoshards(1)]), milestone(1, 3, [cash(100), research('player-speed-multiplier')]), milestone(1, 4, [cash(150), research('cell-spawn-rate')]), milestone(1, 5, [cash(250), chronoshards(3), nextTier(2)]),
  milestone(2, 0, [cash(150), research('cell-magnet')]), milestone(2, 1, [cash(250), research('unlock-speed-booster')]), milestone(2, 2, [cash(400), chronoshards(3), research('speed-booster-duration')]), milestone(2, 3, [cash(650), research('unlock-shockwave')]), milestone(2, 4, [cash(900), chronoshards(6), research('shockwave-size', 'shockwave-frequency')]), milestone(2, 5, [cash(1_250), chronoshards(10), nextTier(3)]),
  milestone(3, 0, [cash(500), research('unlock-slow-aura')]), milestone(3, 1, [cash(750), chronoshards(5), research('slow-aura-effect')]), milestone(3, 2, [cash(1_000), research('cell-increment-per-cell')]), milestone(3, 3, [cash(1_500), chronoshards(10), research('chrono-spawn-rate')]), milestone(3, 4, [cash(2_000), research('slow-aura-range')]), milestone(3, 5, [cash(3_000), chronoshards(15), nextTier(4)]),
  milestone(4, 0, [cash(1_000), research('chrono-lifetime-multiplier')]), milestone(4, 1, [cash(1_500), chronoshards(10), research('building-slots')]), milestone(4, 2, [cash(2_000), research('shield')]), milestone(4, 3, [cash(3_000), chronoshards(15), research('thorn-shield')]), milestone(4, 4, [cash(4_500), research('thorn-shield-duration', 'pushback')]), milestone(4, 5, [cash(6_000), chronoshards(25), research('shield-invulnerability-duration', 'shield-break-explosion'), nextTier(5)]),
  milestone(5, 0, [cash(2_000), research('freezer')]), milestone(5, 1, [cash(3_000), chronoshards(15), research('freezer-duration')]), milestone(5, 2, [cash(4_000), research('regular-lifetime-debuff')]), milestone(5, 3, [cash(6_000), chronoshards(20), research('chaser-range-debuff')]), milestone(5, 4, [cash(8_000), research('creeper-speed-debuff')]), milestone(5, 5, [cash(10_000), chronoshards(30), nextTier(6)]),
  milestone(6, 0, [cash(4_000), research('banger-range-debuff')]), milestone(6, 1, [cash(6_000), chronoshards(20), research('banger-enemy-destruction')]), milestone(6, 2, [cash(8_000), research('shooter-range-debuff')]), milestone(6, 3, [cash(12_000), chronoshards(30), research('shooter-projectile-debuff')]), milestone(6, 4, [cash(16_000), chronoshards(40)]), milestone(6, 5, [cash(20_000), chronoshards(50), nextTier(7)]),
  milestone(7, 0, [cash(8_000), research('porter-interval-debuff')]), milestone(7, 1, [cash(12_000), chronoshards(30), research('magnet-strength-debuff')]), milestone(7, 2, [cash(16_000), research('spore-speed-debuff')]), milestone(7, 3, [cash(24_000), chronoshards(45)]), milestone(7, 4, [cash(32_000), chronoshards(60)]), milestone(7, 5, [cash(40_000), chronoshards(80), nextTier(8)]),
  milestone(8, 0, [cash(16_000), chronoshards(25)]), milestone(8, 1, [cash(24_000), chronoshards(40)]), milestone(8, 2, [cash(32_000), chronoshards(60)]), milestone(8, 3, [cash(48_000), chronoshards(80)]), milestone(8, 4, [cash(64_000), chronoshards(120)]), milestone(8, 5, [cash(100_000), chronoshards(200)]),
]
