// Instructions for adding new research:
// 1. Add a new research object to the "researches" array below.
// 2. Make sure to give it a unique "id" and fill in the other properties as needed.
// 3. If the research has requirements, specify them in the "requirements" property.
// 4. If the research has an effect, specify it in the "effect" property.
// 5. If the research has a cost, specify it in the "cost" property.
// 6. If the research has a duration, specify it in the "duration" property.
// 7. Unless stated explicitly, all researches cost cash.


export const RESEARCH_CONFIG = {
  durationsEnabled: false,
  featureUnlocks: {
    researchLab: { minTier: 2, chronoshardCost: 5 },
    buildingSystem: { minTier: 4, chronoshardCost: 50 },
    weaponry: { minTier: 5, chronoshardCost: 75 },
  },
  maxSlots: 3,
  slotUnlocks: [
    { slot: 2, cost: { currency: 'chronoshards', amount: 50 }, requirements: { minTier: 2 } },
    { slot: 3, cost: { currency: 'chronoshards', amount: 200 }, requirements: { minTier: 3 } },
    { slot: 4, cost: { currency: 'chronoshards', amount: 500 }, requirements: { minTier: 4 } },
    { slot: 5, cost: { currency: 'chronoshards', amount: 1500 }, requirements: { minTier: 4 } },
  ],
  researches: [
    {
      id: 'lucky-find', category: 'Weapons', name: 'Lucky Find', description: 'Weapon cards have a chance to become Lucky Finds and grant 2 cards instead of 1.', maxLevel: 10,
      effect: { stat: 'luckyFindChance', perLevel: 0.02, format: 'percent' }, cost: { currency: 'cash', base: 28_000, multiplier: 1.32, jerk: 1.003 }, duration: { baseMs: 150_000, multiplier: 1.16 }, requirements: { minTier: 5 },
    },
    {
      id: 'weapon-recharge', category: 'Weapons', name: 'Weapon Recharge', description: 'Recharges one charge for each equipped weapon every 8 minutes.', maxLevel: 1,
      cost: { currency: 'cash', base: 40_000, multiplier: 1, jerk: 1 }, duration: { baseMs: 180_000, multiplier: 1 }, requirements: { minTier: 5 },
    },
    {
      id: 'weapon-recharge-rate', category: 'Weapons', name: 'Weapon Recharge Rate', description: 'Reduces weapon recharge time by 30 seconds per level, down to 3 minutes.', maxLevel: 10,
      effect: { stat: 'weaponRechargeReductionSeconds', perLevel: 30, format: 'flat' }, cost: { currency: 'cash', base: 12_000, multiplier: 1.25, jerk: 1.002 }, duration: { baseMs: 150_000, multiplier: 1.18 }, requirements: { minTier: 5, researchId: 'weapon-recharge' },
    },
    {
      id: 'weapon-charge-capacity', category: 'Weapons', name: 'Weapon Charge Capacity', description: 'Increases the maximum stored charges for each equipped weapon by 1.', maxLevel: 4,
      effect: { stat: 'weaponChargeCapacity', perLevel: 1, format: 'flat' }, cost: { currency: 'cash', base: 30_000, multiplier: 1.35, jerk: 1.003 }, duration: { baseMs: 180_000, multiplier: 1.2 }, requirements: { minTier: 5, researchId: 'weapon-recharge' },
    },
    {
      id: 'weapon-slots', category: 'Weapons', name: 'Weapon Slot', description: 'Adds one weapon slot to your round loadout.', maxLevel: 4,
      effect: { stat: 'weaponSlots', perLevel: 1, format: 'flat' }, cost: { currency: 'cash', base: 25_000, multiplier: 1.8, jerk: 1.004 }, duration: { baseMs: 180_000, multiplier: 1.25 }, requirements: { minTier: 3 },
    },
    {
      id: 'player-speed-multiplier',
      category: 'Player Enhancements',
      name: 'Player Speed Multiplier',
      description: 'Increases player movement speed.',
      maxLevel: 50,
      effect: { stat: 'playerSpeedMultiplier', perLevel: 0.02, format: 'percent' },
      cost: { currency: 'cash', base: 100, multiplier: 1.4, jerk: 1.001 },
      duration: { baseMs: 90_000, multiplier: 1.3 },
      requirements: { minTier: 2},
    },
    {
      id: 'unlock-slow-aura',
      category: 'Player Enhancements',
      name: 'Unlock Slow Aura',
      description: 'Unlocks the Slow Aura ability, which slows down nearby enemies within the range.',
      maxLevel: 1,
      cost: { currency: 'cash', base: 10_000, multiplier: 1, jerk: 1 },
      duration: { baseMs: 90_000, multiplier: 1 },
      requirements: { minTier: 3},
    },
    {
      id: 'unlock-orbital-electron',
      category: 'Player Enhancements',
      name: 'Unlock Orbital Electron',
      description: 'Deploys an Electron that orbits your effective range and stuns enemies struck by its electric arc.',
      maxLevel: 1,
      cost: { currency: 'cash', base: 18_000, multiplier: 1, jerk: 1 },
      duration: { baseMs: 120_000, multiplier: 1 },
      requirements: { minTier: 3 },
    },
    {
      id: 'electron-stun-duration',
      category: 'Player Enhancements',
      name: 'Electron Stun Duration',
      description: 'Increases how long enemies hit by the Orbital Electron are stunned.',
      maxLevel: 20,
      effect: { stat: 'electronStunDuration', perLevel: 0.2, format: 'flat' },
      cost: { currency: 'cash', base: 5_000, multiplier: 1.3, jerk: 1.0025 },
      duration: { baseMs: 120_000, multiplier: 1.18 },
      requirements: { minTier: 3, researchId: 'unlock-orbital-electron' },
    },
    {
      id: 'electron-speed',
      category: 'Player Enhancements',
      name: 'Electron Speed',
      description: 'Increases Orbital Electron orbit speed.',
      maxLevel: 20,
      effect: { stat: 'electronSpeed', perLevel: 0.35, format: 'flat' },
      cost: { currency: 'cash', base: 4_000, multiplier: 1.28, jerk: 1.0025 },
      duration: { baseMs: 120_000, multiplier: 1.16 },
      requirements: { minTier: 3, researchId: 'unlock-orbital-electron' },
    },
    {
      id: 'slow-aura-effect',
      category: 'Player Enhancements',
      name: 'Slow Aura Effect',
      description: 'Increases the effect of the Slow Aura ability.',
      maxLevel: 50,
      effect: { stat: 'slowAuraEffect', perLevel: 0.01, format: 'percent' },
      cost: { currency: 'cash', base: 1_000, multiplier: 1.35, jerk: 1.0015 },
      duration: { baseMs: 120_000_000, multiplier: 1.35 },
      requirements: { minTier: 3, researchId: 'unlock-slow-aura' },
    },
    {
      id: 'slow-aura-range',
      category: 'Player Enhancements',
      name: 'Effect Range',
      description: 'Increases the range of every active range-based effect.',
      maxLevel: 99,
      effect: { stat: 'effectRange', perLevel: 0.01, format: 'percent' },
      cost: { currency: 'cash', base: 100, multiplier: 1.15, jerk: 1.0005 },
      duration: { baseMs: 120_000_000, multiplier: 1.35 },
      requirements: { minTier: 2 },
      visibleWhen: { anyResearch: ['unlock-slow-aura', 'cell-magnet', 'pushback'] },
    },
    {
      id: 'cell-spawn-rate',
      category: 'Economy',
      name: 'Cell Spawn Rate',
      description: 'Increases the spawn rate of standard cells.',
      maxLevel: 30,
      effect: { stat: 'cellSpawnRate', perLevel: 0.05, format: 'percent' },
      cost: { currency: 'cash', base: 25, multiplier: 1.8, jerk: 1.003 },
      duration: { baseMs: 120_000_000, multiplier: 1.35 },
      requirements: { minTier: 2 },
    },
    {
      id: 'cell-increment-per-cell',
      category: 'Economy',
      name: 'Cell Increment Per Cell',
      description: 'Each collected Cell increases the standard Cell spawn rate.',
      maxLevel: 50,
      effect: { stat: 'cellSpawnRatePerCell', perLevel: 0.01, format: 'percent' },
      cost: { currency: 'cash', base: 150, multiplier: 1.32, jerk: 1.002 },
      duration: { baseMs: 90_000, multiplier: 1.2 },
      requirements: { minTier: 3 },
    },
    {
      id: 'cash-cell-multiplier',
      category: 'Economy',
      name: 'Cash/Cell Multiplier',
      description: 'Increases the Cash earned from every standard cell.',
      maxLevel: 99,
      effect: { stat: 'cashMultiplier', perLevel: 0.05, format: 'percent' },
      cost: { currency: 'cash', base: 50, multiplier: 1.35, jerk: 1.00075 },
      duration: { baseMs: 60_000, multiplier: 1.25 },
      requirements: { minTier: 1 },
    },
    {
      id: 'initial-cell-count',
      category: 'Economy',
      name: 'Initial Cell',
      description: 'Adds one Cell to the arena at the start of every run.',
      maxLevel: 99,
      effect: { stat: 'initialCellCount', perLevel: 1, format: 'flat' },
      cost: { currency: 'cash', base: 10, multiplier: 1.12, jerk: 1.0002 },
      duration: { baseMs: 30_000, multiplier: 1.08 },
      requirements: { minTier: 1 },
    },
    {
      id: 'cell-magnet',
      category: 'Economy',
      name: 'Cell Magnet',
      description: 'Pulls nearby Cells toward you. Each level increases pull speed.',
      maxLevel: 20,
      effect: { stat: 'cellMagnetSpeed', perLevel: 0.25, format: 'flat' },
      cost: { currency: 'cash', base: 2_000, multiplier: 1.3, jerk: 1.003 },
      duration: { baseMs: 90_000, multiplier: 1.16 },
      requirements: { minTier: 2 },
    },
    {
      id: 'chrono-spawn-rate',
      category: 'Economy',
      name: 'Chrono Spawn Rate',
      description: 'Makes Chrono Cells appear more frequently.',
      maxLevel: 30,
      effect: { stat: 'chronoSpawnRate', perLevel: 0.05, format: 'percent' },
      cost: { currency: 'cash', base: 200, multiplier: 1.1, jerk: 1.002 },
      duration: { baseMs: 120_000_000, multiplier: 1.35 },
      requirements: { minTier: 3 },
    },
    {
      id: 'chrono-lifetime-multiplier',
      category: 'Economy',
      name: 'Chrono Lifetime Multiplier',
      description: 'Increases the lifetime of Chrono Cells.',
      maxLevel: 30,
      effect: { stat: 'chronoLifetimeMultiplier', perLevel: 0.05, format: 'percent' },
      cost: { currency: 'cash', base: 200, multiplier: 1.1, jerk: 1.002 },
      duration: { baseMs: 120_000_000, multiplier: 1.35 },
      requirements: { minTier: 4 },
    },
    {
      id: 'unlock-shockwave',
      category: 'Player Enhancements',
      name: 'Unlock Shockwave',
      description: 'Periodically emits a green shockwave that pushes enemies away.',
      maxLevel: 1,
      cost: { currency: 'cash', base: 20_000, multiplier: 1, jerk: 1 },
      duration: { baseMs: 120_000, multiplier: 1 },
      requirements: { minTier: 2 },
    },
    {
      id: 'shockwave-size',
      category: 'Player Enhancements',
      name: 'Shockwave Size',
      description: 'Increases the range of each Shockwave.',
      maxLevel: 20,
      effect: { stat: 'shockwaveSize', perLevel: 0.1, format: 'percent' },
      cost: { currency: 'cash', base: 100, multiplier: 1.28, jerk: 1.002 },
      duration: { baseMs: 120_000, multiplier: 1.2 },
      requirements: { minTier: 2, researchId: 'unlock-shockwave' },
    },
    {
      id: 'shockwave-frequency',
      category: 'Player Enhancements',
      name: 'Shockwave Frequency',
      description: 'Makes Shockwaves trigger more frequently.',
      maxLevel: 20,
      effect: { stat: 'shockwaveFrequency', perLevel: 0.1, format: 'percent' },
      cost: { currency: 'cash', base: 120, multiplier: 1.28, jerk: 1.002 },
      duration: { baseMs: 120_000, multiplier: 1.2 },
      requirements: { minTier: 2, researchId: 'unlock-shockwave' },
    },
    {
      id: 'shield',
      category: 'Player Enhancements',
      name: 'Shield',
      description: 'Grants one death save per level at the start of every run.',
      maxLevel: 10,
      effect: { stat: 'shieldCharges', perLevel: 1, format: 'flat' },
      cost: { currency: 'cash', base: 125_000, multiplier: 1.45, jerk: 1.004 },
      duration: { baseMs: 180_000, multiplier: 1.25 },
      requirements: { minTier: 4 },
    },
    {
      id: 'building-slots',
      category: 'Building System',
      name: 'Building Slots',
      description: 'Increases the number of buildings you can place in the arena by 1.',
      maxLevel: 7,
      effect: { stat: 'buildingSlots', perLevel: 1, format: 'flat' },
      cost: { currency: 'cash', base: 12_000, multiplier: 1.48, jerk: 1.004 },
      duration: { baseMs: 120_000, multiplier: 1.2 },
      requirements: { minTier: 2 },
    },
    ...[
      ['unlock-speed-booster', 'Unlock Speed Boosters', 'Unlocks Speed Booster pickups that double movement speed.', 1, null, 2],
      ['speed-booster-duration', 'Speed Booster Duration', 'Increases Speed Booster duration.', 20, 'speedBoosterDuration', 2, 'unlock-speed-booster'],
      ['thorn-shield', 'Thorn Shield', 'Unlocks Thorn Shield pickups that grant immunity and destroy enemies on contact.', 1, null, 4],
      ['thorn-shield-duration', 'Thorn Shield Duration', 'Increases Thorn Shield duration.', 20, 'thornShieldDuration', 4, 'thorn-shield'],
      ['freezer', 'Freezer', 'Unlocks Freezer pickups that freeze all enemies.', 1, null, 5],
      ['freezer-duration', 'Freezer Duration', 'Increases Freezer duration.', 20, 'freezerDuration', 5, 'freezer'],
    ].map(([id, name, description, maxLevel, stat, minTier, researchId]) => ({ id, category: 'Boosters', name, description, maxLevel,
      ...(stat ? { effect: { stat, perLevel: 0.25, format: 'flat' } } : {}),
      cost: { currency: 'cash', base: maxLevel === 1 ? 7_000 : 5_000, multiplier: 1.2, jerk: 1.002 },
      duration: { baseMs: 120_000, multiplier: 1.18 }, requirements: { minTier, ...(researchId ? { researchId } : {}) } })),
    {
      id: 'pushback',
      category: 'Player Enhancements',
      name: 'Pushback',
      description: 'Pushes nearby stationary enemies away. Each level increases push speed.',
      maxLevel: 20,
      effect: { stat: 'pushbackSpeed', perLevel: 0.25, format: 'flat' },
      cost: { currency: 'cash', base: 80_000, multiplier: 1.32, jerk: 1.0025 },
      duration: { baseMs: 150_000, multiplier: 1.18 },
      requirements: { minTier: 4 },
    },
    {
      id: 'shield-invulnerability-duration',
      category: 'Player Enhancements',
      name: 'Shield Afterglow',
      description: 'Increases invulnerability time after the Shield breaks.',
      maxLevel: 20,
      effect: { stat: 'shieldInvulnerabilityDuration', perLevel: 0.05, format: 'flat' },
      cost: { currency: 'cash', base: 175_000, multiplier: 1.34, jerk: 1.003 },
      duration: { baseMs: 180_000, multiplier: 1.2 },
      requirements: { minTier: 4, researchLevels: { shield: 1 } },
    },
    {
      id: 'shield-break-explosion',
      category: 'Player Enhancements',
      name: 'Shield Break Explosion',
      description: 'Destroys all enemies within range when the Shield breaks. Each level increases the range.',
      maxLevel: 20,
      effect: { stat: 'shieldBreakExplosionRadius', perLevel: 0.3, format: 'flat' },
      cost: { currency: 'cash', base: 250_000, multiplier: 1.38, jerk: 1.003 },
      duration: { baseMs: 210_000, multiplier: 1.22 },
      requirements: { minTier: 4, researchLevels: { shield: 1 } },
    },
    ...[
      ['regular-lifetime-debuff', 'Regular Decay', 'Reduces Regular enemy lifetime.', 'regularLifetimeDebuff', 5],
      ['chaser-range-debuff', 'Chaser Range Dampener', 'Reduces Chaser detection range.', 'chaserRangeDebuff', 5],
      ['creeper-speed-debuff', 'Creeper Slowdown', 'Reduces Creeper movement speed.', 'creeperSpeedDebuff', 5],
      ['banger-range-debuff', 'Banger Range Dampener', 'Reduces Banger blast range.', 'bangerRangeDebuff', 6],
      ['banger-enemy-destruction', 'Banger Disruption', 'Gives each enemy in a Banger blast a separate destruction chance.', 'bangerEnemyDestroyChance', 6],
      ['shooter-range-debuff', 'Shooter Range Dampener', 'Reduces Shooter firing range.', 'shooterRangeDebuff', 6],
      ['shooter-projectile-debuff', 'Projectile Drag', 'Reduces Shooter projectile speed.', 'shooterProjectileSpeedDebuff', 6],
      ['porter-interval-debuff', 'Porter Delay Field', 'Increases the interval between Porter teleports.', 'porterIntervalBonus', 7],
      ['magnet-strength-debuff', 'Magnet Insulation', 'Reduces Magnet pull strength.', 'magnetStrengthDebuff', 7],
      ['spore-speed-debuff', 'Spore Drag', 'Reduces Spore movement speed.', 'sporeSpeedDebuff', 7],
    ].map(([id, name, description, stat, minTier]) => ({
      id, category: 'Enemy Debuff', name, description, maxLevel: 20,
      effect: { stat, perLevel: stat === 'porterIntervalBonus' ? 0.05 : 0.025, format: 'percent' },
      cost: { currency: 'cash', base: 250_000, multiplier: 1.38, jerk: 1.003 },
      duration: { baseMs: 240_000, multiplier: 1.22 }, requirements: { minTier },
    })),
  ],
}
