export const RESEARCH_CONFIG = {
  maxSlots: 3,
  slotUnlocks: [
    { slot: 2, cost: { currency: 'chronoshards', amount: 100 }, requirements: { minTier: 2 } },
    { slot: 3, cost: { currency: 'chronoshards', amount: 500 }, requirements: { minTier: 3 } },
  ],
  researches: [
    {
      id: 'cell-dividend',
      name: 'Cell Dividend',
      description: 'Increases the Cash earned from every standard cell.',
      maxLevel: 20,
      effect: { stat: 'cashMultiplier', perLevel: 0.05, format: 'percent' },
      cost: { currency: 'cash', base: 50, multiplier: 1.35 },
      duration: { baseMs: 60_000, multiplier: 1.25 },
      requirements: { minTier: 1 },
    },
    {
      id: 'kinetic-drives',
      name: 'Kinetic Drives',
      description: 'Increases player movement speed.',
      maxLevel: 15,
      effect: { stat: 'playerSpeedMultiplier', perLevel: 0.03, format: 'percent' },
      cost: { currency: 'cash', base: 100, multiplier: 1.4 },
      duration: { baseMs: 90_000, multiplier: 1.3 },
      requirements: { minTier: 2, minBankedCells: 10 },
    },
    {
      id: 'temporal-scanner',
      name: 'Temporal Scanner',
      description: 'Makes rare Chrono Cells appear sooner.',
      maxLevel: 12,
      effect: { stat: 'chronoSpawnRate', perLevel: 0.06, format: 'percent' },
      cost: { currency: 'chronoshards', base: 5, multiplier: 1.5 },
      duration: { baseMs: 120_000, multiplier: 1.35 },
      requirements: { minTier: 3, researchLevels: { 'cell-dividend': 3 } },
    },
    {
      id: 'damage-research',
      name: 'Damage Research',
      description: 'Archives a permanent damage bonus for future combat systems.',
      maxLevel: 20,
      effect: { stat: 'damageBonus', perLevel: 0.005, format: 'percent' },
      cost: { currency: 'chronoshards', base: 50_000, multiplier: 1.1 },
      duration: { baseMs: 7_200_000, multiplier: 1.1 },
      requirements: { minTier: 4, researchLevels: { 'kinetic-drives': 5 } },
    },
  ],
}
