export const TIPS = [
  'You will eventually be overwhelmed. Try unlocking new researches to push further.',
  'Keep moving: standing still makes incoming hazards much harder to read.',
  'The final seconds of an enemy lifetime are marked by a blink.',
  'Research upgrades persist between runs, so a short run can still move you forward.',
  'Use the arena edge to reduce the directions enemies can approach from.',
  'Chronoshards are rare, valuable and short-lived. Make sure to grab them before they disappear.',
  'Watch enemy range rings before committing to a path through the arena.',
  'You can unlock boosters later in the game from Research Lab.',
  'After reaching Sector IV, you can unlock the ability to build Buildings to help you in the arena.',
  'Purple enemies are called creepers and they speed up gradually over time. They can be slowed down by static collisions with obstacles.',
  'Red enemies are called chasers and they will actively pursue you. They can be slowed down by static collisions with obstacles.',
  'Yellow enemies are called bangers and they explode after a few seconds.',
  'More cells you collect, the more difficult the game becomes.',
  'New enemies and obstacles are introduced as you progress through the game, so be prepared for new challenges.',
];
